### ISSUE TITLE
FxSound Blocking Spotify Audio Playback

### ISSUE THREAD

**Issue by 0V3RR1DE0** [fxsound2/fxsound-app#121]
### Issue Report: FxSound Blocking Spotify Audio Playback

**Description:**
I am experiencing an issue with FxSound software where it is preventing Spotify from playing audio through my Arctis 5 SteelSeries headset. Despite having all drivers up to date for both FxSound software and the headset, and ensuring that FxSound is updated to the latest version, Spotify is unable to output audio when FxSound is active. 

**Details:**
- Headset: Arctis 5 SteelSeries
- FxSound Version: v1.1.22.0
- Operating System: Windows 11 Pro
  - Edition: Windows 11 Pro
  - Version: 22H2
  - Installed on: 22/11/2023
  - OS build: 22621.3672

**Observations:**
- FxSound functions correctly with other audio sources such as gaming and videos.
- The correct playback device (Arctis 5 Chat) is selected within FxSound.
- Both playback devices (Chat and Game) fail to output Spotify audio when selected in FxSound.
- Spotify briefly outputs sound for a split second when changing the audio device in FxSound, but then fails to play through afterwards.
- Exiting FxSound allows Spotify audio to play normally.

**Duration of Issue:**
This issue has persisted for at least two weeks.

**Troubleshooting Steps:**
- Ensured all drivers are up to date for both FxSound and the Arctis 5 headset.
- Tried selecting both playback devices (Chat and Game) within FxSound, but neither allow Spotify audio to play.
- Restarted the PC, but the issue remains unresolved.

**Additional Information:**
- FxSound was downloaded from their official website.
- This issue only affects Spotify; other audio sources work fine with FxSound.

**Expected Behavior:**
Spotify should be able to play audio normally through the selected playback device in FxSound without any interruptions.

**Impact:**
This issue impacts my ability to enjoy music through Spotify while using FxSound enhancements, limiting the functionality of both applications simultaneously.

**Comment by doolhoofd** [comment]
Is your issue similar to this one?
[https://forum.fxsound.com/t/spotify-app-not-working-with-fx-sound-w10/3134](https://forum.fxsound.com/t/spotify-app-not-working-with-fx-sound-w10/3134)
Very impressive post, by the way. Thanks.

**Comment by 0V3RR1DE0** [comment]
> Is your issue similar to this one?
> [https://forum.fxsound.com/t/spotify-app-not-working-with-fx-sound-w10/3134](https://forum.fxsound.com/t/spotify-app-not-working-with-fx-sound-w10/3134)
> Very impressive post, by the way. Thanks.

Yes same issue

**Comment by doolhoofd** [comment]
Thanks.
Have you been experiencing this since November 2023 on previous versions as well, or did it start after updating to v1.1.22.0? 

> **Troubleshooting Steps:**
> 
> * Ensured all drivers are up to date for both FxSound and the Arctis 5 headset.
> * Tried selecting both playback devices (Chat and Game) within FxSound, but neither allow Spotify audio to play.
> * Restarted the PC, but the issue remains unresolved.

You can find more steps in the standard troubleshooting list; in the meanwhile, I've sent a PM to @bvijay74.

[https://forum.fxsound.com/t/troubleshooting/3105](https://forum.fxsound.com/t/troubleshooting/3105)

**Comment by 0V3RR1DE0** [comment]
> Thanks.
> Have you been experiencing this since November 2023 on previous versions as well, or did it start after updating to v1.1.22.0? 
> 
> [EDIT]
> > **Duration of Issue:** This issue has persisted for at least two weeks.
> 
> So I'm assuming the latter.
> 

The issue started before updating to v1.1.22.0 so it has veen on previous versions. And if i remember correctly i have only taken FxSound into use in 2024. And the software has worked correctly for some time and the issue has appeared now within the last 2 months or so. So the issue doesn't date that far back.

**Comment by bvijay74** [comment]
Hi @0V3RR1DE0,
Through which interface are you connecting the Arctic 5 headset, USB or 3.5mm?
Can you please confirm if Spotify app volume is set in the system volume mixer,
![image](https://github.com/fxsound2/fxsound-app/assets/18183654/ca097a91-29b5-48c4-baf8-3d3ab313e5f1)

**Comment by 0V3RR1DE0** [comment]
> Hi @0V3RR1DE0, Through which interface are you connecting the Arctic 5 headset, USB or 3.5mm? Can you please confirm if Spotify app volume is set in the system volume mixer

Thank you that solved the problem. my spotify app was muted when FxSound was active
![image](https://github.com/fxsound2/fxsound-app/assets/112493528/1deaab2b-6f2c-46e7-8653-f395da30cdff)

Also i am not the best at programming, but can manage. So i might be interested of trying to contribute some features to this project :)

**Comment by bvijay74** [comment]
Glad to hear that the issue is solved. Thanks for your confirmation.
We appreciate your interests in contributing to the code. You can go through the list of issues in GitHub and pick-up anything that interests you. I can provide any guidance that you need to work on it.
