### ISSUE TITLE
How does installer works?

### ISSUE THREAD

**Issue by desumer** [fxsound2/fxsound-app#122]
Hello, Sorry for the silly question.  But, I couldn't figured out how the installer works.  I couldn't find what generates  fxsound_setup.exe or the dfxsetupdrv.exe files.

Any help greatly appreciated,
Thank you

**Comment by bvijay74** [comment]
The installer is developed using Advanced Installer. You can download Advanced Installer from https://www.advancedinstaller.com and openInstaller/fxsound.aip project. The installer custom action uses the script Installer/Script/DfxInstall.vbs. DfxSetupDrv.exe is called from the script. DfxSetupDrv.exe source is not in the repo at present.

**Comment by desumer** [comment]
That clears it out. Thank you for the response.
