### ISSUE TITLE
fx device audio favorability

### ISSUE THREAD

**Issue by iotkido** [fxsound2/fxsound-app#129]
_As _followed__
In FX sound i would like to suggest the ability to select a audio output as the Primary audio output whereby no matter how many bluetooth speakers are connected it will stay on the select audio output

my reasoning stems from a issue i had when i was connecting a old headset as a mic (broke setup) and everytime the speaker(mic) refreshes FXsound will AUTOMATICALLY change the audio output device

**Comment by iotkido** [comment]
thanks for your complaisance to my suggestion,

**Comment by bvijay74** [comment]
Please try the preferred output device feature available in v1.1.24.0 which released for beta testing https://github.com/fxsound2/fxsound-app/raw/beta/release/fxsound_setup.exe

**Comment by bvijay74** [comment]
Preferred device feature available in the latest release
