### ISSUE TITLE
[1.1.23] App crash after settings window

### ISSUE THREAD

**Issue by iDolmatov** [fxsound2/fxsound-app#131]
**Describe the bug**
App crash after open and close settings.
Don't crash without open the settings window.

**To Reproduce**
1. Go to the settings
2. Click on 'x' (close settings)
3. Press the power button (on/off)

**Expected behavior**
Worked FxSound

**Screenshots**
none

**System information**
 - Windows 11 24H2 26241.5000
 - SB X-Fi Go! Pro

**Additional context**
[FxSound.exe.12504.dmp](https://github.com/user-attachments/files/16115982/FxSound.exe.12504.dmp)
[Report.zip](https://github.com/user-attachments/files/16115998/Report.zip)

**Comment by hmcdat** [comment]
same issue

**Comment by Tsury** [comment]
@iDolmatov 
Unrelated, but how are you able to use pre-release versions? Are you building it yourself?

**Comment by bvijay74** [comment]
I have fixed the crash and made a new release. The beta link is the same https://github.com/fxsound2/fxsound-app/raw/beta/release/fxsound_setup.exe
You can find all the releases at https://github.com/fxsound2/fxsound-app/releases

**Comment by Tsury** [comment]
@bvijay74 
Thanks for the beta link.

I can't see any binaries in the github releases page, only source code - that's why I asked whether he built it by himself.
