### ISSUE TITLE
Provide an installer for Fxsound at GitHub releases

### ISSUE THREAD

**Issue by Cccc-owo** [fxsound2/fxsound-app#152]
**Is your feature request related to a problem? Please describe.**
We have to turn to Fxsound website to download the intaller.

**Describe the solution you'd like**
Provide an installer at GitHub releases directly.

**Comment by doolhoofd** [comment]
Check the "Releases" section bottom right:
https://github.com/fxsound2/fxsound-app

**Comment by raddyst** [comment]
> Check the "Releases" section bottom right:
> [fxsound2/fxsound-app](https://github.com/fxsound2/fxsound-app)

Better add link https://github.com/fxsound2/fxsound-app/raw/beta/release/fxsound_setup.exe to readme.md, or un-hide beta folder with compiled binaries to regular users.
fxsound-app-latest.zip takes up three times more space than the installer and is not needed by most people.
