### ISSUE TITLE
Settings file not found!

### ISSUE THREAD

**Issue by sfksuperman** [fxsound2/fxsound-app#153]
I have installed 1.1.22.0 version and tried to upgrade to 1.1.26.0 but getting the error:

**Settings file not found!**

![image](https://github.com/user-attachments/assets/b292a8c0-7910-43ef-b688-e040d5ede5ab)

**Comment by sfksuperman** [comment]
Seems like it has corrupted every version. I uninstalled and re-installed older version 1.1.22.0 but after installation is completed, it gave the same error that Settings file not found!

What should I do now?

**Comment by doolhoofd** [comment]
See: https://github.com/fxsound2/fxsound-app/issues/31

**Comment by sfksuperman** [comment]
Weird but fix the issue by adding myself in the security tab to give permission to the folder **C:\ProgramData\FxSound**
