### ISSUE TITLE
Audio output doesn't change when headphone plug in

### ISSUE THREAD

**Issue by limweidavid** [fxsound2/fxsound-app#154]
**Describe the bug**
My laptop is Dell latitude 5450. When I plug in 3.5mm headphone jack, the audio output still laptop speaker. It doesn't change to headphone.

**To Reproduce**
1. Play youtube video, make sure audio output is laptop speaker.
2. plug in headphone at 3.5mm jack
3. audio will pause a second, like it's switching, but it then eventually played at laptop speaker instead of switching to headphone.

**Expected behavior**
At step #3, it should changed to headphone jack.

**System information**
 - Windows 11
 - Audio device - laptop audio device.
 - FxSound version - latest, i just install.

**Additional context**

**Comment by doolhoofd** [comment]
Hi David, 
If you have v1.1.26.0 - which you can check in the Help tab of the Settings - then you can read the full explanation on the newly-added Preferred Output Device function here:
https://forum.fxsound.com/t/preferred-output-device/3412
Let me know if this helps - or not.

**Comment by bvijay74** [comment]
Hi David,
Since the automatic switch feature is removed and preferred device feature is implemented, you can select the 3.5mm headphone output as the preferred device in settings. This will ensure that the output changes to headphone whenever it is connected.

**Comment by limweidavid** [comment]
It works. Thanks for quick support.

**Comment by doolhoofd** [comment]
Happy to help. Thank you for being polite.
