### ISSUE TITLE
Upon scanning shows as a malware and trojan on virustotal.com, is the software shady or not safe?

### ISSUE THREAD

**Issue by ShouryaD** [fxsound2/fxsound-app#163]
**Describe the bug**
When using virustotal scanning, shows as a trojan and upon closer inspection shows as a malware.  It tries to detect injection attacks.

For reproducing these results:
1. Go to virustotal.com 
2. Upload the latest win build
3. Check in the main section and behaviour section

**Expected behavior**
Not showing any such behaviours and removing if any shady practices present

**Screenshots**

**System information**
 - Windows version: 23H2 Win 11
 - Audio device: Laptop speakers
 - FxSound version : latest

**Additional context**
Please take it as a constructive feedback, else the software looks good

**Comment by doolhoofd** [comment]
See https://github.com/fxsound2/fxsound-app/issues/16 which is identical
See https://forum.fxsound.com/t/fxsound-flagged-as-virus/3414
See https://forum.fxsound.com/t/trojan-win32-drop-jxdhgv-in-your-program/2431

**Comment by bvijay74** [comment]
No virus or malware is getting detected on the latest version 1.1.27.0 by virustotal.
![image](https://github.com/user-attachments/assets/5fb8efc2-fb8d-4ccc-97a9-456bf2b3ce40)

Please share the report of your scanning results.

**Comment by raddyst** [comment]
> Please share the report of your scanning results.

"Trojan" in fxsound_setup.exe ([1.1.26](https://www.virustotal.com/gui/file/782ddda97f69cb004b8e8facddd515611dff52523d04cc5605e6ffe59581080d?nocache=1), [1.1.27](https://www.virustotal.com/gui/file/7dbc411488e4e653769f98b014f2a24b185b24653cee04fa5ed59b03438da7e7?nocache=1) & others).

**Comment by raddyst** [comment]
@bvijay74 register on virustotal for able to view verbose results

![image](https://github.com/user-attachments/assets/6544fa94-13b5-4b83-9f6a-f225c041f08c)
