### ISSUE TITLE
Automatic output device switch is GONE 

### ISSUE THREAD

**Issue by Wassdroid** [fxsound2/fxsound-app#170]
**Describe the bug**
I can no longer set the option to .

**Expected behavior**
When I connect my Bluetooth headphones to my laptop's Bluetooth, Fxsound should automatically switch to it just like it was in prior versions (before version 1.1.26.0)

![Screenshot 2024-09-08 211920](https://github.com/user-attachments/assets/bd4ea494-0f21-48db-b10f-aa37c4e3ab5b)

The option in the red circle above disappeared in 1.1.26.0 and it is annoying because it was an option for whoever liked that behavior. As a result I rolled back to 1.1.22.0.

**Comment by doolhoofd** [comment]
This is the full explanation of the new Preferred Output Device feature. 

https://forum.fxsound.com/t/preferred-output-device/3412

In the latest release v1.1.26.0 a new feature to select preferred output device has been added.
The preferred output device can be selected from FxSound's Settings. 
It can also be selected by passing the device name through the command line option --output. 
For example,
FxSound.exe --output="<speaker name>"
The preferred device feature functions as follows:
1) If preferred device is selected and it is connected during FxSound launch, then audio playback will be through the preferred device.
2) If preferred device is selected but it is not connected when FxSound launches, then audio playback will be through any available device. Once the preferred device is connected again, audio automatically switches to the preferred device.
3) When FxSound is running, if the preferred device is disconnected, then audio playback will switch to an available device. Once the preferred device is connected again, audio automatically switches to the preferred device.
4) If the preferred device is “None”, then audio disconnecting the selected output device will switch the audio to the next available device. Connecting any audio device will not automatically switch the audio playback.
