### ISSUE TITLE
Adding an option in the Settings to enable/disable Launch of FxSound upon Startup

### ISSUE THREAD

**Issue by doolhoofd** [fxsound2/fxsound-app#18]
Forum user @johnepalmer recently posted a request for the addition of an option in FxSound's Settings which would allow users to choose between either enabling or disabling the launch of FxSound on startup.
https://forum.fxsound.com/t/suggestion-for-upgrade-startup-option-general-settings/2141

**Comment by bvijay74** [comment]
On Windows 10 and Windows 11, startup applications are configured through %PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Startup and startup enable/disable through registry setting is not working.
