### ISSUE TITLE
Where can I download old versions of fxSound?

### ISSUE THREAD

**Issue by stalker780** [fxsound2/fxsound-app#184]
Found that 1.1.27 does not work properly with my TWS BT plugs. It requires manual selection of output device each time I switch between Left and Right plugs.

But where can I download older versions? I would like to test v1.1.25, where Automatic switch option was available.

Version history does not contain downloads. And official website allows downloading only the latest version.

**Comment by raddyst** [comment]
> I would like to test v1.1.25,

Download https://codeload.github.com/fxsound2/fxsound-app/zip/refs/tags/v1.1.25.0 & unpack fxsound_setup.exe from \fxsound-app-1.1.25.0.zip\fxsound-app-1.1.25.0\release

**Comment by stalker780** [comment]
Thanks
