### ISSUE TITLE
Can't install (cabinet file  might be corrupted)

### ISSUE THREAD

**Issue by PETER-KIBARA** [fxsound2/fxsound-app#185]
The latest version can't Install. Whenever  i try to install it returns an error saying to verify if it is in that location
`C:\Users\fipol\AppData\Roaming\FxSoundLLC\FxSound\1.1.26.0\install\fxsound1.cab `

1. Download the latest version
2. Run it as administrator

**Expected behavior**
error message saying `source file not found`
**Screenshots**

**System information**
 - Windows version  windows 11
 - FxSound version 1.1.27.0

![Screenshot (2)](https://github.com/user-attachments/assets/3bedbcad-92fc-4eba-820b-3f25b43b1d45)

**Comment by doolhoofd** [comment]
Hello Peter, 
Other tips are described here (third case): https://github.com/fxsound2/fxsound-app/issues/31
Please try those and post back with your results.

**Comment by PETER-KIBARA** [comment]
> Hello Peter, Other tips are described here (third case): #31 Please try those and post back with your results.
that is microsft store
![Screenshot (3)](https://github.com/user-attachments/assets/742225b8-4734-4a01-a258-07048b9a51a8)

**Comment by doolhoofd** [comment]
And the third solution?

Solution shared by @bvijay74:

Extract the installer by running fxsound_setup.exe /extract
Once the files are extracted, you can verify the cab file signature by running
signtool verify /pa fxsound1.cab
Then run fxsound.x64.msi on 64 bit systems or fxsound.msi on 32 bit systems, to install FxSound.

Further info copied from https://forum.fxsound.com/t/verify-file/3467/6 :

To verify the cab file signature, you can install Windows SDK to get signtool and then run the command signtool verify /v /pa fxsound1.cab

You can extract the installer components in fxsound_setup.exe by running fxsound_setup.exe /extract
This will extract the files
fxsound.x64.msi
fxsound.msi
fxsound1.cab

The file properties tab “Digital Signatures” can also be used to confirm the signing,

![image](https://github.com/user-attachments/assets/c9ad6375-10a2-48c8-8588-510bcfb18a53)

If you are facing issues when installing through fxsound_setup.exe, you can run fxsound.x64.msi to install FxSound on 64-bit Windows. If there is any error which prompts you to find fxsound1.cab, you can select the fxsound1.cab that you have extracted.

**Comment by PETER-KIBARA** [comment]
just fix the app i have noticed it's not my device only. @bvijay74

**Comment by raddyst** [comment]
@PETER-KIBARA Maybe you can install fxsound from other user account uses only latin symbols?

![зображення](https://github.com/user-attachments/assets/15cda409-68b9-48c8-80e2-24bb7d8a4d8c)

What alphabet is this?

**Comment by PETER-KIBARA** [comment]
that is a character on my username **`ẞ`** it is not B

**Comment by raddyst** [comment]
> that is a character on my username **`ẞ`** it is not B

Okay, what keyboard layout is this?
