### ISSUE TITLE
The Check for updates option in the Settings menu opens the Changelog webpage instead of updating FxSound

### ISSUE THREAD

**Issue by doolhoofd** [fxsound2/fxsound-app#2]
1. Go to Settings;
2. Click on Help;
3. Scroll down to Maintenance;
4. Click on Check for updates;
5. Browser opens https://www.fxsound.com/changelog 

Desired behavior: 
Clicking Check for updates updates FxSound to the latest version.

**Comment by SecondNewtonLaw** [comment]
> Is there an endpoint for the current version? The download link https://download.fxsound.com/fxsoundlatest doesn't include a version and it would be overkill to parse the HTML on e.g. https://www.fxsound.com/changelog or https://www.fxsound.com/download
> 
> An endpoint to check if an update is actually needed would be neat

Well, I think we may not have to parse HTML, but the download page for fxsound returns a 301 HTTP code, so if we get the location it was "moved" to, we can get the version from the URL, although still it is better to make a dedicated HTTP endpoint for the feature

**Comment by bvijay74** [comment]
This issue is fixed in v1.1.26.0
