### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by michal-a11y** [fxsound2/fxsound-app#203]
**Bug**
can't update Fxsound

**Expected behavior**
A sucessful update
![image](https://github.com/user-attachments/assets/936fbb80-9c8d-4456-9e17-cec2cfba523a)

**System information**
 - Windows 10 Pro 22H2
 - Headphones High Definition audio device
 - v.1.1.16.0

**Additional context**
i was trying to solve it but i failed.

**Comment by raddyst** [comment]
> i was trying to solve it but i failed.

fxsound in windows store not updating now, please remove it and install desktop version from https://github.com/fxsound2/fxsound-app/releases/tag/latest

**Comment by michal-a11y** [comment]
thanks @raddyst
