### ISSUE TITLE
FXSound v1.1.27.0 reinstalled 10/11/2024 will now ONLY run as administrator

### ISSUE THREAD

**Issue by condoghost** [fxsound2/fxsound-app#205]
**Describe the bug**
FXSound will ONLY run as administrator
**To Reproduce**
1. Click desktop icon or click icon in taskbar or click FXSound.exe
2. nothing happens
3. have to right-click run as administrator to open

**Expected behavior**
Click desktop icon or click icon in taskbar or click FXSound.exe

**System information**
 - Windows 11
 - Speakers (Realtek(R) Audio)
 - FxSound version 1.1.27.0

**Comment by SirSAC** [comment]
I have installed same version and I cant reproduce your problem.
I use Windows 11 Enterprise 24H2.
Maybe your windows installation is corrupted or something wrong with it, like I had with other version of 24H2.

**Comment by condoghost** [comment]
Much obliged to you https://github.com/brxndonnn and https://github.com/SirSAC

Solved my issue > I uninstalled then reinstalled. All fine now. Thank-you.

**Comment by condoghost** [comment]
Much obliged to you [brxndonnn](https://github.com/brxndonnn) and [SirSac](https://github.com/SirSAC%5D)

Solved > I uninstalled app then reinstalled it again. Might have been caused by a Windows 11 update and reboot.

All fine now. Thank-you.

**Comment by condoghost** [comment]
Much obliged to you [brxndonnn](https://github.com/brxndonnn) and [SirSac](https://github.com/SirSAC%5D)

Solved > I uninstalled app then reinstalled it again. Might have been caused by a Windows 11 update and reboot.

All fine now. Thank-you.
