### ISSUE TITLE
Notifications re-enabled on windows 10 after being disabled

### ISSUE THREAD

**Issue by arogl** [fxsound2/fxsound-app#44]
**Describe the bug**
[Latest FX Version Shows Annoying Action Center Notifications When disabled, re-enabled after reboot ](https://forum.fxsound.com/t/latest-fx-version-shows-annoying-action-center-notifications-when-switching-playback-devices-and-when-i-completely-disable-all-notifications-for-fxsound-they-re-enable-themselves-ive-tried-everything-any-ideas-thanks/2049)](https://forum.fxsound.com/t/latest-fx-version-shows-annoying-action-center-notifications-when-switching-playback-devices-and-when-i-completely-disable-all-notifications-for-fxsound-they-re-enable-themselves-ive-tried-everything-any-ideas-thanks/2049/17)

@bvijay74 reported in the above linked thread

In Windows 10 I see that disabling FxSound notifications in the system settings doesn’t show the notifications until applications exits.
![image](https://github.com/fxsound2/fxsound-app/assets/1115472/7ab575d6-2615-4aab-ac94-71baae9f06f0)

But OS is persisting the settings and when the application starts again, notifications start to appear unless they are disabled again.
Since the OS behaviour is different from Windows 11, I need to debug this further and implement an OS specific fix.

**To Reproduce**
1. Go to Action centre, Notifications & actions
2. Click on 'disable for FXSound'
3. Reboot
4. Login
5. Notifications enabled after reboot, and displayed in action centre

**Expected behavior**
No notifications after reboot

**System information**
 - Windows 10 December 2023 patch
 - Realtek Speakers, bluetooth headphones
 - FxSound v1.1.20.0 installed from fxsound website

**Additional context**

Reported at the link above, but no GitHub issue created

**Comment by doolhoofd** [comment]
> **Additional context**
> 
> Reported at the link above, but no GitHub issue created

Added on 02/12/2023: https://github.com/fxsound2/fxsound-app/issues/3

> It is important to note that there is a known conflict with Windows' own app-specific notification controls. For example, some users have attempted to disable all of FxSound's notifications through their Windows notification controls, and have reported that this failed to work.
