### ISSUE TITLE
Crackling/popping sound when FXsound is running.

### ISSUE THREAD

**Issue by midnightysaucy** [fxsound2/fxsound-app#45]
Started hearing a consistent crackling sound when running the program, whether or not it's on or off (red button in the menu). It only happens a few seconds after FXsound starts running. When it's not running, the device sound is normal.
I've uninstalled the older version I was using (don't recall which one) and installed the latest one (1.1.20.0). Toggled "Exclusive mode" in the sound settings for all sound devices, as well as changing all formats into 2 channel, 24 bit, 48000 Hz, disabled all enhancements and checked for driver updates. I lowered system volume below 100 for sound devices and tweaked FXsound enhancer and spatial sound settings, no difference there either. There's a post that mentioned a more recent driver date than the one I have.
![image](https://github.com/fxsound2/fxsound-app/assets/155582286/41a65410-04cc-4ddf-9a9c-1ad549872bf0)
![image](https://github.com/fxsound2/fxsound-app/assets/155582286/bb3cf4fc-2557-45e3-a085-01734f471813)
The 2019 version is the one I have.
I'm using windows 10 with 3.5 mm jack headphones (don't know if that matters or not).

**Comment by doolhoofd** [comment]
Hi,
Apologies for this obviously unintended distortion.
You're welcome to create a post on the [FxSound forum](https://forum.fxsound.com/) as well, where I've bannered my standard troubleshooting list to the top of the page.
Does the crackle sound anything like this, perhaps?
https://ufile.io/tgnxg6um

**Comment by midnightysaucy** [comment]
> Hi, Apologies for this obviously unintended distortion. You're welcome to create a post on the [FxSound forum](https://forum.fxsound.com/) as well, where I've bannered my standard troubleshooting list to the top of the page. Does the crackle sound anything like this, perhaps? https://ufile.io/tgnxg6um

I saw the troubleshooting page, tried most of the stuff that could work (haven't used system restore functions)
And the audio sounds like this.
https://vocaroo.com/1ltrcKAdVUKC
It's specifically the pops that happen, the slight distortion is an unrelated effect from the recording.

**Comment by doolhoofd** [comment]
> I saw the troubleshooting page, tried most of the stuff that could work (haven't used system restore functions) 

SysRestore is a last-resort option, which seems like overkill here.

> And the audio sounds like this. https://vocaroo.com/1ltrcKAdVUKC It's specifically the pops that happen, the slight distortion is an unrelated effect from the recording.

Have you tried scanning with [LatencyMon](https://www.resplendence.com/latencymon)?
Feel free to share your results.

> When it's not running, the device sound is normal. 

This is (relatively) good news, because it means that, in any case, there is no damage to your audio or to your system. So, if the problem remains unsolved, you can uninstall FxSound and give another audio enhancer a try; see the list at the end of my list (last, but not list!).

**Comment by midnightysaucy** [comment]
> Have you tried scanning with [LatencyMon](https://www.resplendence.com/latencymon)? Feel free to share your results.

LatencyMon did not report any errors, tried with and without FXsound running, both on and off.

> This is (relatively) good news, because it means that, in any case, there is no damage to your audio or to your system. So, if the problem remains unsolved, you can uninstall FxSound and give another audio enhancer a try; see the list at the end of my list (last, but not list!).

I will try some alternatives, though it seems none of them are as easy to set up and run like FXS. Thanks anyway.

**Comment by midnightysaucy** [comment]
Also out of curiosity, since this popping sound is only caused by the software, could it potentially damage my hardware to use it regardless?

**Comment by doolhoofd** [comment]
> Also out of curiosity, since this popping sound is only caused by the software, could it potentially damage my hardware to use it regardless?

I honestly don't know. I'm not that much of an expert. But you're welcome to ask the question on the forum.

**Comment by midnightysaucy** [comment]
I plugged another audio device to see if it would have the same bug and it did. But after restarting the computer for some reason the pops were gone. I've no idea why that happened since it seemed to be software related, but all's well that ends well I guess. Again, thanks for the support.

**Comment by doolhoofd** [comment]
Thanks for closing this issue yourself, and glad to hear the cracklestorm has passed.
I definitely appreciate your communication skills.
