### ISSUE TITLE
Delay on Modifying Sound

### ISSUE THREAD

**Issue by TMachadoDev** [fxsound2/fxsound-app#46]
**Describe the bug**
When changing some values to change the sound, there is some delay, not sure if is on purpose, if its loading or something, and I don't really know if it happens only to me

**To Reproduce**
Change the values of Ambience, Dynamic Boost etc...

**Expected behavior**
Delay on the modification of sound

**System information**
 - Windows Pro Educational 20H2
 - Intel Smart Sound (I couldn't find what the name is, only shows that)

**Comment by doolhoofd** [comment]
Hi Tiago, 
When I alter my settings, there is no delay...
I composed this first-line-of-defense troubleshooting list on the FxSound forum:
https://forum.fxsound.com/t/troubleshooting-if-youre-having-trouble-please-look-here-first/2510
One of the most relevant tips in your case, would be to run a scan with [LatencyMon](https://www.resplendence.com/latencymon) - and, even better, to run one scan with FxSound On, and another scan with FxSound Off (either deactivated via the main Power button, of after manually disabling the virtual FxSound Speakers device in Windows Sound).
Feel free to post your results here, or on the forum (or both).

**Comment by TMachadoDev** [comment]
Im sorry i had voice meeter running.
