### ISSUE TITLE
Prevent unnecessary UI layout shift between turning on and off

### ISSUE THREAD

**Issue by imdj** [fxsound2/fxsound-app#47]
**Describe the bug**
When turning the program on, a component for an audio wave visualizer appears, and when turning the program off, it disappears this causes the layout to shift which affects the experience of the user and predictability when interacting with the software.

**To Reproduce**
1. Open FxSound
2. Press the turn on/off button
3. Notice how the layout shift and the user need to adjust to new placement for the elements

**Expected behavior**
It'd be a smoother experience if there were no noticable layout shift (by adding some placeholder or spacing)

**Screenshots**
![fxsound-layout-shift](https://github.com/fxsound2/fxsound-app/assets/69906094/24d6acd5-a83d-4151-8898-bde108e18acc)

**System information**
 - Windows 10

**Comment by doolhoofd** [comment]
Hello Imad,
This was fixed a while ago, your screenshots are from an old version. 
The latest version is v1.1.20.0, available from fxsound.com .
