### ISSUE TITLE
Adding a zero-processing Preset to the default Presets

### ISSUE THREAD

**Issue by doolhoofd** [fxsound2/fxsound-app#48]
Forum member 1FF proposed adding a blank / zero-processing Preset to the drop-down menu of existing pre-loaded / factory default ones.

https://forum.fxsound.com/t/language-options/27/117

Example:

![zero processing](https://github.com/fxsound2/fxsound-app/assets/151672060/4fafa1a8-7f33-41c1-a520-4fe5f9a3e500)

**Comment by sihunqu123** [comment]
Currently, there is a workaround: just disable the FxSound for the 0-processing

**Comment by doolhoofd** [comment]
> Currently, there is a workaround: just disable the FxSound for the 0-processing

The envisioned goal was to have a kind of "blank slate" to start processing from, and to create new custom Presets from.

**Comment by bvijay74** [comment]
Zero processing preset is added in release v1.1.21.0
