### ISSUE TITLE
Conflict(s) between certain key combinations/symbols and FxSound's (customizable) shortcuts

### ISSUE THREAD

**Issue by doolhoofd** [fxsound2/fxsound-app#53]
Forum member mumpi noted that on German/Austrian/Swiss keyboard layouts, the standard Ctrl+Alt+Q shortcut to toggle FxSound On/Off conflicts with the creation of the "@" symbol; and also proposed several possible solutions:

- Change the key combination for shortcuts: "You can go to CTRL+SHIFT or ALT-SHIFT as default, which does not default to characters on standard layouts."
- Have the shortcuts disabled by default on first launch;
- Display a warning pop-up on first launch to notify users of the conflict.

Sources:
https://forum.fxsound.com/t/new-shortcuts/2551/6/
https://forum.fxsound.com/t/new-shortcuts/2551/8/

**Comment by NullDev** [comment]
I wanted to work on this issue, given that I do use a German keyboard layout and I can reproduce that bug (e.g. I can't type "@" when the shortcut is active).

However I'm unable to find where the default shortcut is specified. 
I think I understand how [FxController::getHotkey](https://github.com/fxsound2/fxsound-app/blob/main/fxsound/Source/GUI/FxController.cpp#L1278-L1289) works and I can see how they are [generally defined](https://github.com/fxsound2/fxsound-app/blob/main/fxsound/Source/GUI/FxSettingsDialog.cpp#L174), but I don't see when/how the default shortcuts are registered. Is this some JUICE specific stuff with [app_secure_properties_](https://github.com/fxsound2/fxsound-app/blob/2fdb1e15506bc41601c068aa8eebb6b6a336324a/fxsound/Source/Utils/Settings/Settings.cpp#L32) & [ApplicationProperties](https://docs.juce.com/master/classApplicationProperties.html)? I couldn't find anything in Projucer either.

Sorry for the ping, but do you maybe have an idea @bvijay74 ?

**Comment by bvijay74** [comment]
Hi @NullDev 
We can prevent RegisterHotkey being called for the hotkey combinations which result in a valid character from the key combinations. I have found a solution for this by calling ToUnicodeEx API. I will check-in my fix.

**Comment by bvijay74** [comment]
Fix is available in commit [68ab65d](https://github.com/fxsound2/fxsound-app/commit/68ab65d346975824fbdb51a54d6e2fbb5e144eac)

**Comment by doolhoofd** [comment]
"Insults are the arguments employed by those who are in the wrong." - Jean-Jacques Rousseau
