### ISSUE TITLE
Allow locking a preset to a particular device

### ISSUE THREAD

**Issue by androidghosh** [fxsound2/fxsound-app#61]
**Is your feature request related to a problem? Please describe.**
_Even when I change the audio device, for eg- my laptop speakers to my bluetooth headphone, the preset stays the same, which is a problem because the preset that sounds good on laptop speaker won't sound good in Headphone_

**Describe the solution you'd like**
_There should be a preset lock button, it will lock a preset to a device, and if enabled, each time the device gets connected, it will automatically switch the preset, even if fxsound is minimized._

**Describe alternatives you've considered**
_none_

**Comment by doolhoofd** [comment]
See: https://github.com/fxsound2/fxsound-app/issues/9
