### ISSUE TITLE
@ sign is disabled when using shotcuts 

### ISSUE THREAD

**Issue by Teesieb** [fxsound2/fxsound-app#62]
**Describe the bug**

**To Reproduce**
4. Select '...'
5. See error

**Expected behavior**

**Screenshots**

**System information**
 - Windows version
 - Audio device

**Additional context**

**Comment by Teesieb** [comment]
I had Trouble to write an Email because the @ sign is inpossible on German keyboard.
If u Disable Shotcuts in settings u can use @ 
Nice Programm but this sucks. 
I hope i can help a little 👍

**Comment by doolhoofd** [comment]
Thank you.
The team is aware of this issue and working on a fix.
See:
https://github.com/fxsound2/fxsound-app/issues/53
and
https://forum.fxsound.com/t/new-shortcuts/2551/
