### ISSUE TITLE
Crash if Windows Audio service is stopped

### ISSUE THREAD

**Issue by Unknown78** [fxsound2/fxsound-app#69]
**Describe the bug**

If the service `Audiosrv` / `Windows Audio` stopped or restarted it will crash FxSound.

<hr>

**To Reproduce**

1. Launch and Enable FxSound
2. Go to Task Manager > Services
3.  Find `Audiosrv`
4. Right click > Restart

<hr>

**Expected behavior**

To prevent it from crash, there should be control loop mechanism to ensure that Windows Audio service is running properly.

- If it has started then ignore it.
- If it has stopped then start it.
- If it is still restarting then wait it.

<hr>

**System information**
 - Windows version: Windows 11 Pro for Workstations x64 23H2 10.0.22631.3155
 - Audio device: Realtek ALC269 
 - Audio driver: Generic Microsoft driver, because it allows to switch the output to speaker or to headphone
   _[Related case of why the need of generic one](https://www.techpowerup.com/forums/threads/realtek-codec-inability-to-separate-speaker-outputs-with-realtek-driver.247171/)_.
<hr>

**Additional context**

Sometimes the volume slider is not working. I could slide, but there's no change to physical acoustic volume.
And restarting the Windows Audio service solves it.

**Comment by doolhoofd** [comment]
I understand your request.

Messing with standard Windows processes like the Windows Audio Service, is done at your own risk, and it is not FxSound's role or obligation to mess with those services or to take over any of that risk.

**Comment by Unknown78** [comment]
There is no malicious intent of messing to begin with.

FxSound is codependent on Windows Audio service.
It has obligation to check whether it could depends reliably.
This should be the basic of robust dependency control.

**Comment by doolhoofd** [comment]
Under normal circumstances, there is no need at all to tinker with the Windows Audio Service.

**Comment by Unknown78** [comment]
@doolhoofd Thank you for being very helpful.

In case someone needs it, this is a script to auto restart the service and the program.
It's a wrapper for PowerShell commands.

Why PowerShell?
- It needs Admin rights to restart the service.
- It prompts  to be run as Admin and relaunch it automatically.
- It supports custom installation path of `FxSound.exe` with `$ImagePath` variable.
   Make sure it's enclosed with single quotes `'...'`, otherwise undefined behavior, stop system processes, and then BSOD.

Why wrapper?
- It avoids unnecessarily set the PowerShell execution policy.

Just run it from cmd/terminal or launch it as `.bat`.
```batch
@powershell -WindowStyle Hidden -c "if( ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) ){ $ImagePath = 'C:\Program Files\FxSound LLC\FxSound\FxSound.exe'; Get-Process | Where-Object {$_.Path -eq $ImagePath} | Stop-Process -Force -Name {$_.ProcessName}; Restart-Service AudioSrv -Force; Start-Process $ImagePath } else { Start-Process "%~f0 %*" -Verb RunAs -WindowStyle Hidden }"
```

**Comment by Unknown78** [comment]
It's no longer crashed as I tested it with version `1.2.6.0`, I don't know since when.
