### ISSUE TITLE
System tray icon changes according to FxSound status on/off/processing

### ISSUE THREAD

**Issue by raddyst** [fxsound2/fxsound-app#78]
Perhaps a different icon is needed here, w/o black background.

![image](https://github.com/fxsound2/fxsound-app/assets/8584929/d822ac8e-4329-40e8-96a6-a7730f88938e) ![image](https://github.com/fxsound2/fxsound-app/assets/8584929/2b92f458-0397-4372-88e6-0fea9aff8d40) ![image](https://github.com/fxsound2/fxsound-app/assets/8584929/cc9161c6-b9ab-4493-abc1-728b72183d66)

**Comment by doolhoofd** [comment]
If the background was white or transparent, the second image you shared, would just be a void.
So how would you improve this?

**Comment by raddyst** [comment]
Don't know, but first needs - synchronize colors between on/off button and tray icon:

![image](https://github.com/fxsound2/fxsound-app/assets/8584929/c2b732e9-e4fd-4c5d-b8bf-856afc290682)  ![image](https://github.com/fxsound2/fxsound-app/assets/8584929/dd85d034-7359-4e31-b843-9a8003b2840c)  ![image](https://github.com/fxsound2/fxsound-app/assets/8584929/e176da67-eb63-4172-824a-95eabd8a7003)

ps.  Post new version on forum.fxsound.com - english-speaking users will better talk to you about the design)

**Comment by doolhoofd** [comment]
Note that there are three icon states: 

Logo is grey when FxSound is Off,
Logo is white when FxSound is On,
Logo is purple when FxSound is On and music plays.

**Comment by raddyst** [comment]
> Note that there are three icon states:
> 
> Logo is grey when FxSound is Off, Logo is white when FxSound is On, Logo is purple when FxSound is On and music plays.

i'm know, but why "on/off button" is White and "tray icon" is gray when fxsound off?

**Comment by doolhoofd** [comment]
The white color of the Power button in the Off state was simply carried over from all the previous versions.
The Settings and Minimize buttons next to it, are also white.
 
> ps. Post new version on forum.fxsound.com - english-speaking users will better talk to you about the design)

The new version hasn't been released yet. Some final details still need to be smoothed out.

**Comment by raddyst** [comment]
> The white color of the Power button in the Off state was simply carried over from all the previous versions.

In previous version the tray icon was static.

> The Settings and Minimize buttons next to it, are also white.

![image](https://github.com/fxsound2/fxsound-app/assets/8584929/0e66b835-61bb-455c-8a39-d00393f6ebab)  ![image](https://github.com/fxsound2/fxsound-app/assets/8584929/0fd01a3c-e824-4122-a874-1f8c4ac243c1)


ps. the color of on/off button and tray icon must be the same.

**Comment by raddyst** [comment]
> The new version hasn't been released yet. Some final details still need to be smoothed out.

You can post beta-version on forum - there are only 19 subscribers here

**Comment by doolhoofd** [comment]
> In previous version the tray icon was static.

Yes, this is a newly-added update.

> ps. the color of on/off button and tray icon must be the same.

Says who? Why?

> You can post beta-version on forum - there are only 19 subscribers here

I don't have any access to the new version or the beta version, and it is not up to me to share or publish it.

**Comment by raddyst** [comment]
> Says who? Why?
> 

This is my opinion - it would be logical

> I don't have any access to the new version or the beta version

You can't download https://github.com/fxsound2/fxsound-app/archive/refs/tags/v1.1.21.0.zip ?

**Comment by doolhoofd** [comment]
> You can't download https://github.com/fxsound2/fxsound-app/archive/refs/tags/v1.1.21.0.zip ?

No, because I don't have a GitHub account! 

;-P

**Comment by raddyst** [comment]
> No, because I don't have a GitHub account!

https://github.com/fxsound2/fxsound-app/releases/tag/v1.1.21.0 available without github authorization

**Comment by bvijay74** [comment]
The color scheme using in the FxSound application window is,
red - on/enabled
white - off
gray - disabled due to off

So, when FxSound is off the rest of the UI controls become gray which means disabled, that is the sliders cannot be used. We cannot make the power button itself gray, because that might indicate that the power button is disabled and it cannot be clicked.
