### ISSUE TITLE
New shortcuts modifiers conflicts with games

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [fxsound2/fxsound-app#95]
**Describe the bug**
the new shortcuts conflict with games. eg. shooters:

CTRL (crouch) + SHIFT (RUN) + Q (switch weapon) => fx sound turns off, i don't hear the footsteps, so I die.. damn
CTRL (crouch) + SHIFT (RUN) + E (interact) => fx sound opens/close, game looses focus, so I die.. damn
CTRL (crouch) + SHIFT (RUN) + A (strafe left) => preset changes to bass boost, grenade explodes to me, my ears implode, so I die.. damn
CTRL (crouch) + SHIFT (RUN) + Z (prone) => preset changes to voice, I hear only chitchat, but no footsteps and bullets, so I die.. damn
CTRL (crouch) + SHIFT (RUN) + W (forward) => switches from headset to speakers, all room goes BOOM, I freak out and I die.. damn

As you can see, in all scenarios I die in horrible ways. I was actually been demoted from platinum league to rusted iron in ranked tournaments, because of this bug. I thought I was a freakin noob.

Took me a while to figure out what was going on, as I used ctrl + alt + key since forever, and wasn't notified the shortcuts are changing.

Since there are way less german keyboard layouts out there than standard US layout, users should have been prompted to change the shortcut if keyboard layout wasn't US or at least notify them of the change.

Nevertheless, after changing back to standard shortcuts, I was promoted to diamond thanks to the gaming preset which lets me hear all the noobs footsteps. Thanks fxsound for that!

Related change issue: https://github.com/fxsound2/fxsound-app/issues/53

**System information**
 - Windows version: win 11 23H2
 - fxsound v1.1.22.0

**Comment by doolhoofd** [comment]
Hi Void,
The changes made with each update are always outlined in the [Changelog](https://www.fxsound.com/changelog) on the official website.

**Comment by doolhoofd** [comment]
Because I am able to evaluate the quality of someone's arguments, and decided there is no need to pander to your request, since the changes are outlined in the Changelog, and the customizable shortcuts are not in need of a health hazard warning like a pack of cigarettes.
If it took you a while to figure out what was going on, then I'd suggest you get sharper, instead of demanding the inverse from us.

**Comment by doolhoofd** [comment]
Kudos on editing out your own provocation. I appreciate it!

**Comment by doolhoofd** [comment]
> one thing is to announce on the website were nobody looks, and another is to inform the user upon update on pretty major behavior change.
> 
> why would you close this issue, when it is definitely affecting all gamers? wtf

FxSound always displays this pop-up linking to the [Changelog](https://www.fxsound.com/changelog) page after an update,

![what's new](https://github.com/fxsound2/fxsound-app/assets/151672060/7a2bd1bc-a9a4-4a32-8bf1-6220bcee8963)

There is also a direct link to it in the Help tab of the Settings menu,

![help tab](https://github.com/fxsound2/fxsound-app/assets/151672060/05efbc8f-069f-4e98-8949-8ebae6fc45d3)
